server:
  port: 8082

spring:
  application:
    name: booking-service
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true

resilience4j:
  circuitbreaker:
    instances:
      movieServiceCB:
        sliding-window-size: 5
        minimum-number-of-calls: 3
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 2
        automatic-transition-from-open-to-half-open-enabled: true
  timelimiter:
    instances:
      movieServiceCB:
        timeout-duration: 3s

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
  health:
    circuitbreakers:
      enabled: true

logging:
  level:
    com.bookingservice: DEBUG

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/